/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_api_v1_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_api_v1_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deal */
        get: operations["get_deal_api_v1_deals__deal_id__get"];
        put?: never;
        post?: never;
        /** Delete Deal */
        delete: operations["delete_deal_api_v1_deals__deal_id__delete"];
        options?: never;
        head?: never;
        /** Update Deal */
        patch: operations["update_deal_api_v1_deals__deal_id__patch"];
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_deals__deal_id__documents_get"];
        put?: never;
        /** Upload Documents */
        post: operations["upload_documents_api_v1_deals__deal_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pages/{page_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_api_v1_documents__document_id__pages__page_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/render/{page_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Render Page */
        get: operations["render_page_api_v1_documents__document_id__render__page_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download File */
        get: operations["download_file_api_v1_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/reparse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reparse Document */
        post: operations["reparse_document_api_v1_documents__document_id__reparse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Table */
        get: operations["get_table_api_v1_tables__table_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_v1_deals__deal_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Index Status */
        get: operations["get_index_status_api_v1_deals__deal_id__index_get"];
        put?: never;
        /** Start Index */
        post: operations["start_index_api_v1_deals__deal_id__index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facts */
        get: operations["list_facts_api_v1_deals__deal_id__facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fact */
        get: operations["get_fact_api_v1_facts__fact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Fact */
        patch: operations["patch_fact_api_v1_facts__fact_id__patch"];
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deal Graph */
        get: operations["deal_graph_api_v1_deals__deal_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["get_entity_api_v1_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Entity */
        post: operations["merge_entity_api_v1_entities__entity_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Split Entity Endpoint */
        post: operations["split_entity_endpoint_api_v1_entities__entity_id__split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deal Events */
        get: operations["deal_events_api_v1_deals__deal_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo */
        post: operations["create_demo_api_v1_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Block */
        Block: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            kind: components["schemas"]["BlockKind"];
            /** Text */
            text: string;
            /** Bbox */
            bbox: number[] | null;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
        };
        /**
         * BlockKind
         * @enum {string}
         */
        BlockKind: "heading" | "paragraph" | "list_item" | "table" | "figure" | "caption" | "header" | "footer" | "slide_note";
        /** Body_upload_documents_api_v1_deals__deal_id__documents_post */
        Body_upload_documents_api_v1_deals__deal_id__documents_post: {
            /** Files */
            files: string[];
            /** Paths */
            paths?: string[] | null;
        };
        /** Cell */
        Cell: {
            /** Id */
            id: string;
            /** Row */
            row: number;
            /** Col */
            col: number;
            /** Text */
            text: string;
            /** Value Num */
            value_num: string | null;
            /** Value Date */
            value_date: string | null;
            /** Bbox */
            bbox: number[] | null;
            /** Ref */
            ref: string | null;
        };
        /**
         * ContradictionSummary
         * @description Placeholder shape for the P4 Contradiction engine (§5).
         */
        ContradictionSummary: {
            /** Id */
            id: string;
            /** Rule Id */
            rule_id: string;
            /** Metric */
            metric: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
        };
        /** Deal */
        Deal: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Company Name */
            company_name: string;
            stage: components["schemas"]["DealStage"];
            /** Currency */
            currency: string;
            /** Fiscal Year End Month */
            fiscal_year_end_month: number;
            /** Proposed Round Usd */
            proposed_round_usd: string | null;
            /** Proposed Pre Money Usd */
            proposed_pre_money_usd: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DealCreate */
        DealCreate: {
            /** Name */
            name: string;
            /** Company Name */
            company_name: string;
            /** @default series_b */
            stage: components["schemas"]["DealStage"];
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Fiscal Year End Month
             * @default 12
             */
            fiscal_year_end_month: number;
            /** Proposed Round Usd */
            proposed_round_usd?: number | string | null;
            /** Proposed Pre Money Usd */
            proposed_pre_money_usd?: number | string | null;
        };
        /**
         * DealStage
         * @enum {string}
         */
        DealStage: "seed" | "series_a" | "series_b" | "growth" | "buyout" | "other";
        /** DealUpdate */
        DealUpdate: {
            /** Name */
            name?: string | null;
            /** Company Name */
            company_name?: string | null;
            stage?: components["schemas"]["DealStage"] | null;
            /** Currency */
            currency?: string | null;
            /** Fiscal Year End Month */
            fiscal_year_end_month?: number | null;
            /** Proposed Round Usd */
            proposed_round_usd?: number | string | null;
            /** Proposed Pre Money Usd */
            proposed_pre_money_usd?: number | string | null;
        };
        /** DemoRequest */
        DemoRequest: {
            /** Name */
            name?: string | null;
        };
        /** DemoResponse */
        DemoResponse: {
            /** Deal Id */
            deal_id: string;
            /** Run Id */
            run_id: string | null;
        };
        /**
         * DocStatus
         * @enum {string}
         */
        DocStatus: "queued" | "parsing" | "parsed" | "failed" | "unsupported";
        /**
         * DocType
         * @enum {string}
         */
        DocType: "deck" | "financial_statement" | "bank_statement" | "customer_list" | "contract" | "cap_table" | "board_deck" | "email" | "legal" | "other" | "unknown";
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Blob Id */
            blob_id: string;
            /** Parent Document Id */
            parent_document_id: string | null;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Ext */
            ext: string;
            doc_type: components["schemas"]["DocType"];
            status: components["schemas"]["DocStatus"];
            /** Error */
            error: string | null;
            /** Page Count */
            page_count: number;
            /** Language */
            language: string | null;
            /** Doc Date */
            doc_date: string | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentDetail */
        DocumentDetail: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Blob Id */
            blob_id: string;
            /** Parent Document Id */
            parent_document_id: string | null;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Ext */
            ext: string;
            doc_type: components["schemas"]["DocType"];
            status: components["schemas"]["DocStatus"];
            /** Error */
            error: string | null;
            /** Page Count */
            page_count: number;
            /** Language */
            language: string | null;
            /** Doc Date */
            doc_date: string | null;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Pages */
            pages: components["schemas"]["PageSummary"][];
            /** Tables */
            tables: components["schemas"]["TableSummary"][];
        };
        /** DocumentUpload */
        DocumentUpload: {
            /** Documents */
            documents: components["schemas"]["Document"][];
            /** Skipped */
            skipped: components["schemas"]["SkippedFile"][];
        };
        /** Entity */
        Entity: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Type */
            type: components["schemas"]["EntityType"] | string;
            /** Canonical Name */
            canonical_name: string;
            /** Normalized Name */
            normalized_name: string;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /** Merged Into Id */
            merged_into_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EntityAlias */
        EntityAlias: {
            /** Id */
            id: string;
            /** Entity Id */
            entity_id: string;
            /** Alias */
            alias: string;
            /** Normalized */
            normalized: string;
            /** Source Document Id */
            source_document_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EntityDetail */
        EntityDetail: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Type */
            type: components["schemas"]["EntityType"] | string;
            /** Canonical Name */
            canonical_name: string;
            /** Normalized Name */
            normalized_name: string;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /** Merged Into Id */
            merged_into_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Aliases
             * @default []
             */
            aliases: components["schemas"]["EntityAlias"][];
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Relations
             * @default []
             */
            relations: components["schemas"]["Relation"][];
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["Fact"][];
        };
        /** EntityMerge */
        EntityMerge: {
            /** Into Entity Id */
            into_entity_id: string;
        };
        /** EntitySplit */
        EntitySplit: {
            /** Alias Ids */
            alias_ids: string[];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "company" | "customer" | "contract" | "revenue_stream" | "invoice" | "person" | "shareholder" | "security_class" | "liability" | "bank_account" | "employee" | "market";
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Document Id */
            document_id: string;
            /** Page No */
            page_no: number;
            /** Chunk Id */
            chunk_id: string | null;
            /** Cell Id */
            cell_id: string | null;
            /** Char Start */
            char_start: number | null;
            /** Char End */
            char_end: number | null;
            /** Quote */
            quote: string;
            /** Bbox */
            bbox: number[] | null;
            /** Target Kind */
            target_kind: string | null;
            /** Target Id */
            target_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename?: string | null;
        };
        /**
         * ExtractionMethod
         * @enum {string}
         */
        ExtractionMethod: "table" | "llm" | "derived" | "manual";
        /** Fact */
        Fact: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Subject Entity Id */
            subject_entity_id: string;
            /** Metric */
            metric: string;
            /** Value */
            value: string | null;
            /** Value Text */
            value_text: string | null;
            unit: components["schemas"]["Unit"];
            /** Currency */
            currency: string | null;
            period_type: components["schemas"]["PeriodType"];
            /** Period Start */
            period_start: string | null;
            /** Period End */
            period_end: string | null;
            /** As Of */
            as_of: string | null;
            /** Source Kind */
            source_kind: string;
            extraction_method: components["schemas"]["ExtractionMethod"];
            /** Confidence */
            confidence: number;
            /** Is Authoritative */
            is_authoritative: boolean;
            /** Superseded By Id */
            superseded_by_id: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Contested
             * @default false
             */
            contested: boolean;
        };
        /** FactDetail */
        FactDetail: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Subject Entity Id */
            subject_entity_id: string;
            /** Metric */
            metric: string;
            /** Value */
            value: string | null;
            /** Value Text */
            value_text: string | null;
            unit: components["schemas"]["Unit"];
            /** Currency */
            currency: string | null;
            period_type: components["schemas"]["PeriodType"];
            /** Period Start */
            period_start: string | null;
            /** Period End */
            period_end: string | null;
            /** As Of */
            as_of: string | null;
            /** Source Kind */
            source_kind: string;
            extraction_method: components["schemas"]["ExtractionMethod"];
            /** Confidence */
            confidence: number;
            /** Is Authoritative */
            is_authoritative: boolean;
            /** Superseded By Id */
            superseded_by_id: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Contested
             * @default false
             */
            contested: boolean;
            /**
             * Derived From
             * @default []
             */
            derived_from: components["schemas"]["Fact"][];
            /**
             * Contradictions
             * @default []
             */
            contradictions: components["schemas"]["ContradictionSummary"][];
        };
        /** FactPage */
        FactPage: {
            /** Items */
            items: components["schemas"]["Fact"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FactPatch */
        FactPatch: {
            /** Notes */
            notes?: string | null;
            /** Is Authoritative */
            is_authoritative?: boolean | null;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["Entity"][];
            /** Edges */
            edges: components["schemas"]["Relation"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexResponse */
        IndexResponse: {
            /** Job Id */
            job_id: string;
        };
        /** IndexStatus */
        IndexStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "indexing" | "ready" | "stale" | "empty";
            /** Chunk Count */
            chunk_count: number;
            /** Embedded Count */
            embedded_count: number;
            /** Embedding Model */
            embedding_model: string | null;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string | null;
            kind: components["schemas"]["JobKind"];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /** Error */
            error: string | null;
            /** Idempotency Key */
            idempotency_key: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "parse_document" | "classify_document" | "index_deal" | "extract_facts" | "build_graph" | "detect_contradictions" | "run_pipeline" | "generate_output";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /** Page */
        Page: {
            /** Page No */
            page_no: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Is Scanned */
            is_scanned: boolean;
            /** Sheet Name */
            sheet_name: string | null;
            /** Text */
            text: string;
            /** Blocks */
            blocks: components["schemas"]["Block"][];
            /** Tables */
            tables: components["schemas"]["Table"][];
        };
        /** PageSummary */
        PageSummary: {
            /** Page No */
            page_no: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Is Scanned */
            is_scanned: boolean;
            /** Sheet Name */
            sheet_name: string | null;
        };
        /**
         * PeriodType
         * @enum {string}
         */
        PeriodType: "point" | "month" | "quarter" | "fiscal_year" | "ttm" | "custom";
        /** Relation */
        Relation: {
            /** Id */
            id: string;
            /** Deal Id */
            deal_id: string;
            /** Type */
            type: components["schemas"]["RelationType"] | string;
            /** Source Entity Id */
            source_entity_id: string;
            /** Target Entity Id */
            target_entity_id: string;
            /** Attrs */
            attrs: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RelationType
         * @enum {string}
         */
        RelationType: "has_customer" | "has_contract" | "generates_revenue" | "billed_by" | "owns_shares" | "employs" | "owes" | "banks_with" | "competes_in";
        /** ReparseResponse */
        ReparseResponse: {
            /** Job Id */
            job_id: string;
        };
        /** SearchFilters */
        SearchFilters: {
            /** Doc Types */
            doc_types?: components["schemas"]["DocType"][] | null;
            /** Document Ids */
            document_ids?: string[] | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page No */
            page_no: number;
            /** Text */
            text: string;
            /** Score */
            score: number;
            /** Bm25 Rank */
            bm25_rank: number | null;
            /** Dense Rank */
            dense_rank: number | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /**
             * K
             * @default 10
             */
            k: number;
            filters?: components["schemas"]["SearchFilters"] | null;
            /** Rerank */
            rerank?: ("none" | "llm" | "cross-encoder") | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchHit"][];
        };
        /** SkippedFile */
        SkippedFile: {
            /** Filename */
            filename: string;
            /** Reason */
            reason: string;
        };
        /** Table */
        Table: {
            /** Id */
            id: string;
            /** Page Id */
            page_id: string;
            /** Block Id */
            block_id: string | null;
            /** Order */
            order: number;
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            /** Header Row */
            header_row: number | null;
            /** Sheet Name */
            sheet_name: string | null;
            /** Column Types */
            column_types: string[];
            /** Bbox */
            bbox: number[] | null;
            /** Title */
            title: string | null;
        };
        /** TableDetail */
        TableDetail: {
            /** Id */
            id: string;
            /** Page Id */
            page_id: string;
            /** Block Id */
            block_id: string | null;
            /** Order */
            order: number;
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            /** Header Row */
            header_row: number | null;
            /** Sheet Name */
            sheet_name: string | null;
            /** Column Types */
            column_types: string[];
            /** Bbox */
            bbox: number[] | null;
            /** Title */
            title: string | null;
            /** Cells */
            cells: (components["schemas"]["Cell"] | null)[][];
        };
        /** TableSummary */
        TableSummary: {
            /** Id */
            id: string;
            /** Page No */
            page_no: number;
            /** Order */
            order: number;
            /** N Rows */
            n_rows: number;
            /** N Cols */
            n_cols: number;
            /** Header Row */
            header_row: number | null;
            /** Sheet Name */
            sheet_name: string | null;
            /** Column Types */
            column_types: string[];
            /** Title */
            title: string | null;
        };
        /**
         * Unit
         * @enum {string}
         */
        Unit: "currency" | "percent" | "count" | "months" | "ratio" | "text";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_deals_api_v1_deals_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deal_api_v1_deals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deal_api_v1_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deal_api_v1_deals__deal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deal_api_v1_deals__deal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_deals__deal_id__documents_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DocStatus"] | null;
                doc_type?: components["schemas"]["DocType"] | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_api_v1_deals__deal_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_v1_deals__deal_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUpload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_v1_documents__document_id__pages__page_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_page_api_v1_documents__document_id__render__page_no__get: {
        parameters: {
            query?: {
                scale?: number;
            };
            header?: never;
            path: {
                document_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_v1_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reparse_document_api_v1_documents__document_id__reparse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReparseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_table_api_v1_tables__table_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_deals__deal_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_index_status_api_v1_deals__deal_id__index_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_index_api_v1_deals__deal_id__index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facts_api_v1_deals__deal_id__facts_get: {
        parameters: {
            query?: {
                metric?: string | null;
                period_from?: string | null;
                period_to?: string | null;
                source_kind?: components["schemas"]["DocType"] | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fact_api_v1_facts__fact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_fact_api_v1_facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_graph_api_v1_deals__deal_id__graph_get: {
        parameters: {
            query?: {
                types?: string | null;
                limit?: number;
                format?: string | null;
            };
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_v1_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_entity_api_v1_entities__entity_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityMerge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    split_entity_endpoint_api_v1_entities__entity_id__split_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntitySplit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_events_api_v1_deals__deal_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_api_v1_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DemoRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
