"""facts_graph_tables

Revision ID: 21768d57a624
Revises: d4d47b54c38d
Create Date: 2026-09-28 07:17:19.195368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21768d57a624'
down_revision: Union[str, Sequence[str], None] = 'd4d47b54c38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('merged_into_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_deal_id'), 'entity', ['deal_id'], unique=False)
    op.create_index(op.f('ix_entity_normalized_name'), 'entity', ['normalized_name'], unique=False)
    op.create_index('uq_entity_deal_type_name', 'entity', ['deal_id', 'type', 'normalized_name'], unique=True, sqlite_where=sa.text('merged_into_id IS NULL'), postgresql_where=sa.text('merged_into_id IS NULL'))
    op.create_table('entity_alias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('normalized', sa.String(length=300), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_alias_entity_id'), 'entity_alias', ['entity_id'], unique=False)
    op.create_table('fact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('extraction_method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['fact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_deal_id'), 'fact', ['deal_id'], unique=False)
    op.create_index('ix_fact_deal_metric_period', 'fact', ['deal_id', 'metric', 'period_start', 'period_end'], unique=False)
    op.create_index(op.f('ix_fact_metric'), 'fact', ['metric'], unique=False)
    op.create_table('relation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('attrs', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'source_entity_id', 'target_entity_id', name='uq_relation_type_src_tgt')
    )
    op.create_index(op.f('ix_relation_deal_id'), 'relation', ['deal_id'], unique=False)
    op.create_index(op.f('ix_relation_source_entity_id'), 'relation', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relation_target_entity_id'), 'relation', ['target_entity_id'], unique=False)
    op.create_table('fact_link',
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('parent_fact_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.ForeignKeyConstraint(['parent_fact_id'], ['fact.id'], ),
    sa.PrimaryKeyConstraint('fact_id', 'parent_fact_id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('cell_id', sa.String(length=36), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('target_kind', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('chunk_id IS NOT NULL OR cell_id IS NOT NULL', name='ck_evidence_chunk_or_cell'),
    sa.ForeignKeyConstraint(['cell_id'], ['cell.id'], ),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_deal_id'), 'evidence', ['deal_id'], unique=False)
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_index('ix_evidence_target', 'evidence', ['target_kind', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_target', table_name='evidence')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_deal_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('fact_link')
    op.drop_index(op.f('ix_relation_target_entity_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_source_entity_id'), table_name='relation')
    op.drop_index(op.f('ix_relation_deal_id'), table_name='relation')
    op.drop_table('relation')
    op.drop_index(op.f('ix_fact_metric'), table_name='fact')
    op.drop_index('ix_fact_deal_metric_period', table_name='fact')
    op.drop_index(op.f('ix_fact_deal_id'), table_name='fact')
    op.drop_table('fact')
    op.drop_index(op.f('ix_entity_alias_entity_id'), table_name='entity_alias')
    op.drop_table('entity_alias')
    op.drop_index('uq_entity_deal_type_name', table_name='entity', sqlite_where=sa.text('merged_into_id IS NULL'), postgresql_where=sa.text('merged_into_id IS NULL'))
    op.drop_index(op.f('ix_entity_normalized_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_deal_id'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
