"""deal table

Revision ID: 3ce461fc76ef
Revises: 5c1a43edb23a
Create Date: 2026-09-23 15:47:41.498136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce461fc76ef'
down_revision: Union[str, Sequence[str], None] = '5c1a43edb23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fiscal_year_end_month', sa.Integer(), nullable=False),
    sa.Column('proposed_round_usd', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('proposed_pre_money_usd', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal')
    # ### end Alembic commands ###
