"""llm_call_table

Revision ID: 44af39dd3ab1
Revises: 21768d57a624
Create Date: 2026-09-28 10:41:54.825985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44af39dd3ab1'
down_revision: Union[str, Sequence[str], None] = '21768d57a624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_call_agent_run_id', 'llm_call', ['agent_run_id'], unique=False)
    op.create_index('ix_llm_call_deal_id', 'llm_call', ['deal_id'], unique=False)
    op.create_index('ix_llm_call_request_hash', 'llm_call', ['request_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_call_request_hash', table_name='llm_call')
    op.drop_index('ix_llm_call_deal_id', table_name='llm_call')
    op.drop_index('ix_llm_call_agent_run_id', table_name='llm_call')
    op.drop_table('llm_call')
    # ### end Alembic commands ###
