"""document tables

Revision ID: 458dc3a1bb68
Revises: 284d6b64fa18
Create Date: 2026-09-23 21:43:31.786075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458dc3a1bb68'
down_revision: Union[str, Sequence[str], None] = '284d6b64fa18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('blob_id', sa.String(length=36), nullable=False),
    sa.Column('parent_document_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['blob.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['parent_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'blob_id', 'path', name='uq_document_deal_blob_path')
    )
    op.create_index('ix_document_deal_doc_type', 'document', ['deal_id', 'doc_type'], unique=False)
    op.create_index(op.f('ix_document_deal_id'), 'document', ['deal_id'], unique=False)
    op.create_index('ix_document_deal_status', 'document', ['deal_id', 'status'], unique=False)
    op.create_table('page',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_no', name='uq_page_document_no')
    )
    op.create_index(op.f('ix_page_document_id'), 'page', ['document_id'], unique=False)
    op.create_table('block',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'order', name='uq_block_page_order')
    )
    op.create_index(op.f('ix_block_page_id'), 'block', ['page_id'], unique=False)
    op.create_table('data_table',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('block_id', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('column_types', sa.JSON(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_table_page_id'), 'data_table', ['page_id'], unique=False)
    op.create_table('cell',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('ref', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['data_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'row', 'col', name='uq_cell_table_row_col')
    )
    op.create_index(op.f('ix_cell_table_id'), 'cell', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_table_id'), table_name='cell')
    op.drop_table('cell')
    op.drop_index(op.f('ix_data_table_page_id'), table_name='data_table')
    op.drop_table('data_table')
    op.drop_index(op.f('ix_block_page_id'), table_name='block')
    op.drop_table('block')
    op.drop_index(op.f('ix_page_document_id'), table_name='page')
    op.drop_table('page')
    op.drop_index('ix_document_deal_status', table_name='document')
    op.drop_index(op.f('ix_document_deal_id'), table_name='document')
    op.drop_index('ix_document_deal_doc_type', table_name='document')
    op.drop_table('document')
    op.drop_table('blob')
    # ### end Alembic commands ###
