"""chunk_table

Revision ID: d4d47b54c38d
Revises: 458dc3a1bb68
Create Date: 2026-09-28 03:19:34.892960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d47b54c38d'
down_revision: Union[str, Sequence[str], None] = '458dc3a1bb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('block_ids', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('table_id', sa.String(length=36), nullable=True),
    sa.Column('row_start', sa.Integer(), nullable=True),
    sa.Column('row_end', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['data_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_deal_doc_page', 'chunk', ['deal_id', 'document_id', 'page_no'], unique=False)
    op.create_index(op.f('ix_chunk_deal_id'), 'chunk', ['deal_id'], unique=False)
    op.create_index(op.f('ix_chunk_document_id'), 'chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunk_text_hash'), 'chunk', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_text_hash'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_document_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_deal_id'), table_name='chunk')
    op.drop_index('ix_chunk_deal_doc_page', table_name='chunk')
    op.drop_table('chunk')
    # ### end Alembic commands ###
